apiVersion: v1
data:
  MYSQL_DATABASE: {{ .Values.db.name }}
  MYSQL_PASSWORD: {{ .Values.db.password }}
  MYSQL_ROOT_PASSWORD: {{ .Values.db.rootPassword }}
  MYSQL_USER: {{ .Values.db.user }}
kind: ConfigMap
metadata:
  name: mysql-env
  namespace: {{ .Release.Namespace }}
