apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.db.host }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: db
spec:
  ports:
  - port: 3306
    name: web
  clusterIP: None
  selector:
    app: mysql
