apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wordpress
  name: wordpress
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.wordpress.replicas }}
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      volumes:
        - name: wp-volume
          persistentVolumeClaim:
            claimName: wordpress
      containers:
      - image: {{ .Values.wordpress.image }}
        name: wordpress
        env:
          - name: WORDPRESS_DB_HOST
            value: mysql-0.{{ .Values.db.host }}
            # value: {{ .Values.db.host }}
          - name: WORDPRESS_DB_USER
            valueFrom:
              configMapKeyRef:
                name: mysql-env
                key: MYSQL_USER
          - name: WORDPRESS_DB_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: mysql-env
                key: MYSQL_PASSWORD
          - name: WORDPRESS_DB_NAME
            valueFrom:
              configMapKeyRef:
                name: mysql-env
                key: MYSQL_DATABASE
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: /var/www/html
            name: wp-volume

