apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Mi
  hostPath:
    path: /data/wordpress/
